// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/marketplace": {
    params: {};
  };
  "/marketplace/browse": {
    params: {};
  };
  "/marketplace/become-seller": {
    params: {};
  };
  "/marketplace/categories": {
    params: {};
  };
  "/marketplace/categories/:slug": {
    params: {
      "slug": string;
    };
  };
  "/marketplace/featured": {
    params: {};
  };
  "/marketplace/sellers": {
    params: {};
  };
  "/marketplace/sellers/:id": {
    params: {
      "id": string;
    };
  };
  "/marketplace/listings/:id": {
    params: {
      "id": string;
    };
  };
  "/marketplace/cart": {
    params: {};
  };
  "/marketplace/orders": {
    params: {};
  };
  "/marketplace/purchases": {
    params: {};
  };
  "/marketplace/wishlist": {
    params: {};
  };
  "/marketplace/messages": {
    params: {};
  };
  "/marketplace/subscriptions": {
    params: {};
  };
  "/marketplace/payment/success": {
    params: {};
  };
  "/marketplace/payment/failure": {
    params: {};
  };
  "/marketplace/seller/dashboard": {
    params: {};
  };
  "/marketplace/seller/analytics": {
    params: {};
  };
  "/marketplace/seller/listings": {
    params: {};
  };
  "/marketplace/seller/listings/new": {
    params: {};
  };
  "/marketplace/seller/listings/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/marketplace/admin": {
    params: {};
  };
  "/marketplace/admin/analytics": {
    params: {};
  };
  "/marketplace/admin/moderation": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
  "/project/:id/text-editor": {
    params: {
      "id": string;
    };
  };
  "/project/:id/media-bin": {
    params: {
      "id": string;
    };
  };
  "/project/:id/transitions": {
    params: {
      "id": string;
    };
  };
  "/project/:id/effects": {
    params: {
      "id": string;
    };
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/projects/*": {
    params: {
      "*": string;
    };
  };
  "/api/assets/*": {
    params: {
      "*": string;
    };
  };
  "/api/storage/*": {
    params: {
      "*": string;
    };
  };
  "/api/ai": {
    params: {};
  };
  "/api/ai/generate-image": {
    params: {};
  };
  "/api/ai/generate-video": {
    params: {};
  };
  "/api/media/download": {
    params: {};
  };
  "/api/media/unsplash/search": {
    params: {};
  };
  "/api/media/spotify/search": {
    params: {};
  };
  "/learn": {
    params: {};
  };
  "/roadmap": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/marketplace" | "/marketplace/browse" | "/marketplace/become-seller" | "/marketplace/categories" | "/marketplace/categories/:slug" | "/marketplace/featured" | "/marketplace/sellers" | "/marketplace/sellers/:id" | "/marketplace/listings/:id" | "/marketplace/cart" | "/marketplace/orders" | "/marketplace/purchases" | "/marketplace/wishlist" | "/marketplace/messages" | "/marketplace/subscriptions" | "/marketplace/payment/success" | "/marketplace/payment/failure" | "/marketplace/seller/dashboard" | "/marketplace/seller/analytics" | "/marketplace/seller/listings" | "/marketplace/seller/listings/new" | "/marketplace/seller/listings/:id/edit" | "/marketplace/admin" | "/marketplace/admin/analytics" | "/marketplace/admin/moderation" | "/login" | "/projects" | "/profile" | "/project/:id" | "/project/:id/text-editor" | "/project/:id/media-bin" | "/project/:id/transitions" | "/project/:id/effects" | "/api/auth/*" | "/api/projects/*" | "/api/assets/*" | "/api/storage/*" | "/api/ai" | "/api/ai/generate-image" | "/api/ai/generate-video" | "/api/media/download" | "/api/media/unsplash/search" | "/api/media/spotify/search" | "/learn" | "/roadmap" | "/privacy" | "/terms" | "/*";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/";
  };
  "routes/marketplace.tsx": {
    id: "routes/marketplace";
    page: "/marketplace";
  };
  "routes/marketplace.browse.tsx": {
    id: "routes/marketplace.browse";
    page: "/marketplace/browse";
  };
  "routes/marketplace.become-seller.tsx": {
    id: "routes/marketplace.become-seller";
    page: "/marketplace/become-seller";
  };
  "routes/marketplace.categories.tsx": {
    id: "routes/marketplace.categories";
    page: "/marketplace/categories";
  };
  "routes/marketplace.categories.$slug.tsx": {
    id: "routes/marketplace.categories.$slug";
    page: "/marketplace/categories/:slug";
  };
  "routes/marketplace.featured.tsx": {
    id: "routes/marketplace.featured";
    page: "/marketplace/featured";
  };
  "routes/marketplace.sellers.tsx": {
    id: "routes/marketplace.sellers";
    page: "/marketplace/sellers";
  };
  "routes/marketplace.sellers.$id.tsx": {
    id: "routes/marketplace.sellers.$id";
    page: "/marketplace/sellers/:id";
  };
  "routes/marketplace.listings.$id.tsx": {
    id: "routes/marketplace.listings.$id";
    page: "/marketplace/listings/:id";
  };
  "routes/marketplace.cart.tsx": {
    id: "routes/marketplace.cart";
    page: "/marketplace/cart";
  };
  "routes/marketplace.orders.tsx": {
    id: "routes/marketplace.orders";
    page: "/marketplace/orders";
  };
  "routes/marketplace.purchases.tsx": {
    id: "routes/marketplace.purchases";
    page: "/marketplace/purchases";
  };
  "routes/marketplace.wishlist.tsx": {
    id: "routes/marketplace.wishlist";
    page: "/marketplace/wishlist";
  };
  "routes/marketplace.messages.tsx": {
    id: "routes/marketplace.messages";
    page: "/marketplace/messages";
  };
  "routes/marketplace.subscriptions.tsx": {
    id: "routes/marketplace.subscriptions";
    page: "/marketplace/subscriptions";
  };
  "routes/marketplace.payment.success.tsx": {
    id: "routes/marketplace.payment.success";
    page: "/marketplace/payment/success";
  };
  "routes/marketplace.payment.failure.tsx": {
    id: "routes/marketplace.payment.failure";
    page: "/marketplace/payment/failure";
  };
  "routes/marketplace.seller.dashboard.tsx": {
    id: "routes/marketplace.seller.dashboard";
    page: "/marketplace/seller/dashboard";
  };
  "routes/marketplace.seller.analytics.tsx": {
    id: "routes/marketplace.seller.analytics";
    page: "/marketplace/seller/analytics";
  };
  "routes/marketplace.seller.listings.tsx": {
    id: "routes/marketplace.seller.listings";
    page: "/marketplace/seller/listings";
  };
  "routes/marketplace.seller.listings.new.tsx": {
    id: "routes/marketplace.seller.listings.new";
    page: "/marketplace/seller/listings/new";
  };
  "routes/marketplace.seller.listings.$id.edit.tsx": {
    id: "routes/marketplace.seller.listings.$id.edit";
    page: "/marketplace/seller/listings/:id/edit";
  };
  "routes/marketplace.admin.tsx": {
    id: "routes/marketplace.admin";
    page: "/marketplace/admin";
  };
  "routes/marketplace.admin.analytics.tsx": {
    id: "routes/marketplace.admin.analytics";
    page: "/marketplace/admin/analytics";
  };
  "routes/marketplace.admin.moderation.tsx": {
    id: "routes/marketplace.admin.moderation";
    page: "/marketplace/admin/moderation";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/project.$id.tsx": {
    id: "routes/project.$id";
    page: "/project/:id" | "/project/:id/text-editor" | "/project/:id/media-bin" | "/project/:id/transitions" | "/project/:id/effects";
  };
  "components/timeline/MediaBin.tsx": {
    id: "components/timeline/MediaBin";
    page: "/project/:id";
  };
  "components/media/TextEditor.tsx": {
    id: "components/media/TextEditor";
    page: "/project/:id/text-editor";
  };
  "components/timeline/MediaBinPage.tsx": {
    id: "components/timeline/MediaBinPage";
    page: "/project/:id/media-bin";
  };
  "components/media/Transitions.tsx": {
    id: "components/media/Transitions";
    page: "/project/:id/transitions";
  };
  "components/media/EffectsPage.tsx": {
    id: "components/media/EffectsPage";
    page: "/project/:id/effects";
  };
  "routes/api.auth.$.tsx": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/api.projects.$.tsx": {
    id: "routes/api.projects.$";
    page: "/api/projects/*";
  };
  "routes/api.assets.$.tsx": {
    id: "routes/api.assets.$";
    page: "/api/assets/*";
  };
  "routes/api.storage.$.tsx": {
    id: "routes/api.storage.$";
    page: "/api/storage/*";
  };
  "routes/api.ai.tsx": {
    id: "routes/api.ai";
    page: "/api/ai";
  };
  "routes/api.ai.generate-image.tsx": {
    id: "routes/api.ai.generate-image";
    page: "/api/ai/generate-image";
  };
  "routes/api.ai.generate-video.tsx": {
    id: "routes/api.ai.generate-video";
    page: "/api/ai/generate-video";
  };
  "routes/api.media.download.tsx": {
    id: "routes/api.media.download";
    page: "/api/media/download";
  };
  "routes/api.media.unsplash.search.tsx": {
    id: "routes/api.media.unsplash.search";
    page: "/api/media/unsplash/search";
  };
  "routes/api.media.spotify.search.tsx": {
    id: "routes/api.media.spotify.search";
    page: "/api/media/spotify/search";
  };
  "routes/learn.tsx": {
    id: "routes/learn";
    page: "/learn";
  };
  "routes/roadmap.tsx": {
    id: "routes/roadmap";
    page: "/roadmap";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "./NotFound.tsx": {
    id: "NotFound";
    page: "/*";
  };
};